variables:
  HTML_REPORT_SUBJECT:
    required: false
    type: string
    default:
    description: "Enter a custom report subject name."
  AUDIT_AWS_S3_ALERT_LIST:
    description: "Which alerts would you like to check for? Default is all S3 alerts. Choices are s3-inventory,s3-allusers-write,s3-allusers-write-acp,s3-allusers-read,s3-authenticatedusers-write,s3-authenticatedusers-write-acp,s3-authenticatedusers-read,s3-logging-disabled,s3-world-open-policy-delete,s3-world-open-policy-get,s3-world-open-policy-list,s3-world-open-policy-put,s3-world-open-policy-all,s3-only-ip-based-policy,s3-authenticatedusers-access"
    required: false
    type: array
    default:
       - s3-allusers-read
       - s3-logging-disabled
       - s3-authenticatedusers-read
       - s3-authenticatedusers-write-acp
       - s3-authenticatedusers-write
       - s3-allusers-write-acp
       - s3-allusers-write
       - s3-allusers-full-control
  AUDIT_AWS_RDS_ALERT_LIST:
    required: false
    type: array
    default:
        - rds-db-instance-unencrypted 
        - rds-db-snapshot-unencrypted 
        - rds-short-backup-retention-period 
        - rds-no-auto-minor-version-upgrade 
        - rds-db-publicly-accessible 
    description: "Which rules would you like to run? Possible values are rds-db-instance-unencrypted rds-db-snapshot-unencrypted rds-inventory rds-short-backup-retention-period rds-no-auto-minor-version-upgrade rds-db-publicly-accessible"
  AUDIT_AWS_EC2_ALERT_LIST:
    required: false
    type: array
    default:
      - ec2-ip-address-whitelisted 
      - ec2-vpc-flow-logs
      - ec2-unrestricted-traffic
    description: "Which rules would you like to run? Possible values are ec2-inventory-instances ec2-inventory-security-groups ec2-ip-address-whitelisted ec2-unrestricted-traffic ec2-TCP-1521-0.0.0.0/0 ec2-TCP-3306-0.0.0.0/0 ec2-TCP-5432-0.0.0.0/0 ec2-TCP-27017-0.0.0.0/0 ec2-TCP-1433-0.0.0.0/0 ec2-TCP-3389-0.0.0.0/0 ec2-TCP-22-0.0.0.0/0 ec2-TCP-5439-0.0.0.0/0 ec2-TCP-23 ec2-TCP-21 ec2-TCP-20 ec2-TCP-8080 ec2-ports-range ec2-not-used-security-groups ec2-default-security-group-traffic ec2-vpc-flow-logs"
  AUDIT_AWS_IAM_ALERT_LIST:
    required: false
    type: array
    default:
      - iam-passwordreuseprevention
      - iam-expirepasswords
      - iam-password-policy-uppercase
      - iam-password-policy-lowercase
      - iam-password-policy-symbol
      - iam-password-policy-number
      - iam-password-policy-min-length
      - iam-support-role
      - iam-unusediamgroup
      - iam-omnipotent-policy
    description: "Which rules would you like to run? Possible values are iam-inventory-users iam-inventory-roles iam-inventory-policies iam-inventory-groups iam-unusediamgroup iam-multiple-keys iam-root-multiple-keys iam-inactive-key-no-rotation iam-active-key-no-rotation iam-missing-password-policy iam-passwordreuseprevention iam-expirepasswords iam-no-mfa iam-root-active-password iam-user-attached-policies iam-password-policy-uppercase iam-password-policy-lowercase iam-password-policy-symbol iam-password-policy-number iam-password-policy-min-length iam-root-access-key-1 iam-root-access-key-2 iam-cloudbleed-passwords-not-rotated iam-support-role iam-user-password-not-used iam-unused-access iam-no-hardware-mfa-root iam-active-root-user iam-mfa-password-holders manual-ensure-security-questions manual-detailed-billing iam-root-key-access iam-root-no-mfa manual-strategic-iam-roles iam-initialization-access-key manual-contact-details manual-security-contact manual-resource-instance-access manual-full-privilege-user manual-appropriate-sns-subscribers manual-least-access-routing-tables iam-user-is-admin iam-instance-role-is-admin"  
  AUDIT_AWS_KMS_ALERT_LIST:
    required: false
    type: array
    default:
      - kms-key-rotates # not_violation cis_id:2.8
      - kms-unused
    description: "Which rules would you like to run? Possible values are kms-inventory kms-key-rotates kms-unused"
  AUDIT_AWS_CLOUDTRAIL_ALERT_LIST:
    description: "Which alerts would you like to check for? Default is all Cloudtrail alerts. Possible values are cloudtrail-inventory,cloudtrail-service-disabled,cloudtrail-log-file-validating,cloudtrail-logs-cloudwatch,cloudtrail-no-global-trails, cloudtrail-logs-encrypted"
    required: false
    type: array
    default:
      - cloudtrail-log-file-validating
      - cloudtrail-logs-encrypted   
  AUDIT_AWS_IAM_DAYS_PASSWORD_UNUSED:
    description: "Number of days for which password has not been used"
    required: true
    type: string
    default: "30"
  AUDIT_AWS_REGIONS:
    description: "List of AWS regions to check. Default is all regions. Choices are us-east-1,us-east-2,us-west-1,us-west-2,ca-central-1,ap-south-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-northeast-1,eu-central-1,eu-west-1,eu-west-1,sa-east-1"
    required: true
    type: array
    default:
        - us-west-1
  FILTERED_OBJECTS:
    description: "JSON object of string or regex of aws objects to include or exclude and tag in audit"
    required: false
    type: string
    default:
