variables:
  HTML_REPORT_SUBJECT:
    required: false
    type: string
    default:
    description: "Enter a custom report subject name."
  AUDIT_AWS_S3_ALERT_LIST:
    description: "Which alerts would you like to check for? Default is all S3 alerts. Choices are s3-inventory,s3-allusers-write,s3-allusers-write-acp,s3-allusers-read,s3-authenticatedusers-write,s3-authenticatedusers-write-acp,s3-authenticatedusers-read,s3-logging-disabled,s3-world-open-policy-delete,s3-world-open-policy-get,s3-world-open-policy-list,s3-world-open-policy-put,s3-world-open-policy-all,s3-only-ip-based-policy,s3-authenticatedusers-access"
    required: false
    type: array
    default:
       - s3-allusers-read
  AUDIT_AWS_EC2_ALERT_LIST:
    required: false
    type: array
    default:
      - ec2-ip-address-whitelisted 
    description: "Which rules would you like to run? Possible values are ec2-inventory-instances ec2-inventory-security-groups ec2-ip-address-whitelisted ec2-unrestricted-traffic ec2-TCP-1521-0.0.0.0/0 ec2-TCP-3306-0.0.0.0/0 ec2-TCP-5432-0.0.0.0/0 ec2-TCP-27017-0.0.0.0/0 ec2-TCP-1433-0.0.0.0/0 ec2-TCP-3389-0.0.0.0/0 ec2-TCP-22-0.0.0.0/0 ec2-TCP-5439-0.0.0.0/0 ec2-TCP-23 ec2-TCP-21 ec2-TCP-20 ec2-TCP-8080 ec2-ports-range ec2-not-used-security-groups ec2-default-security-group-traffic ec2-vpc-flow-logs"
  AUDIT_AWS_EC2_REGIONS:
    description: "List of AWS regions to check. Default is all regions. Choices are us-east-1,us-east-2,us-west-1,us-west-2,ca-central-1,ap-south-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-northeast-1,eu-central-1,eu-west-1,eu-west-1,sa-east-1"
    required: true
    type: array
    default:
        - us-west-1
  FILTERED_OBJECTS:
    description: "JSON object of string or regex of aws objects to include or exclude and tag in audit"
    required: false
    type: string
    default:
