variables:
  HTML_REPORT_SUBJECT:
    required: false
    type: string
    default:
    description: "Enter a custom report subject name."
  AUDIT_AWS_S3_ALERT_LIST:
    description: "Which alerts would you like to check for? Default is all S3 alerts. Choices are s3-inventory,s3-allusers-write,s3-allusers-write-acp,s3-allusers-read,s3-authenticatedusers-write,s3-authenticatedusers-write-acp,s3-authenticatedusers-read,s3-logging-disabled,s3-world-open-policy-delete,s3-world-open-policy-get,s3-world-open-policy-list,s3-world-open-policy-put,s3-world-open-policy-all,s3-only-ip-based-policy,s3-authenticatedusers-access"
    required: false
    type: array
    default:
       - s3-allusers-read
  AUDIT_AWS_RDS_ALERT_LIST:
    required: false
    type: array
    default:
        - rds-db-instance-unencrypted 
        - rds-db-snapshot-unencrypted 
        - rds-short-backup-retention-period 
        - rds-no-auto-minor-version-upgrade 
        - rds-db-publicly-accessible 
    description: "Which rules would you like to run? Possible values are rds-db-instance-unencrypted rds-db-snapshot-unencrypted rds-inventory rds-short-backup-retention-period rds-no-auto-minor-version-upgrade rds-db-publicly-accessible"
  AUDIT_AWS_EC2_ALERT_LIST:
    required: false
    type: array
    default:
      - ec2-ip-address-whitelisted 
    description: "Which rules would you like to run? Possible values are ec2-inventory-instances ec2-inventory-security-groups ec2-ip-address-whitelisted ec2-unrestricted-traffic ec2-TCP-1521-0.0.0.0/0 ec2-TCP-3306-0.0.0.0/0 ec2-TCP-5432-0.0.0.0/0 ec2-TCP-27017-0.0.0.0/0 ec2-TCP-1433-0.0.0.0/0 ec2-TCP-3389-0.0.0.0/0 ec2-TCP-22-0.0.0.0/0 ec2-TCP-5439-0.0.0.0/0 ec2-TCP-23 ec2-TCP-21 ec2-TCP-20 ec2-TCP-8080 ec2-ports-range ec2-not-used-security-groups ec2-default-security-group-traffic ec2-vpc-flow-logs"
  AUDIT_AWS_IAM_ALERT_LIST:
    required: false
    type: array
    default:
      - iam-unusediamgroup #
      - iam-multiple-keys #
      - iam-root-multiple-keys #
      - iam-inactive-key-no-rotation #
      - iam-active-key-no-rotation # cis_id:1.4
      - iam-missing-password-policy #
      - iam-passwordreuseprevention # cis_id:1.10
      - iam-expirepasswords # cis_id:1.11
      - iam-no-mfa #
      - iam-root-active-password #
      - iam-user-attached-policies # cis_id:1.16
      - iam-password-policy-uppercase # cis_id:1.05
      - iam-password-policy-lowercase # cis_id:1.06
      - iam-password-policy-symbol # cis_id:1.07
      - iam-password-policy-number # cis_id:1.08
      - iam-password-policy-min-length # cis_id:1.9
      - iam-cloudbleed-passwords-not-rotated #
      - iam-support-role # cis_id:1.22
      - iam-omnipotent-policy # cis_id 1.24
      - iam-user-password-not-used # not_violation
      - iam-unused-access # not_violation cis_id:1.3
      - iam-no-hardware-mfa-root # cis_id:1.14
      - iam-active-root-user # not_violation cis_id:1.1
      - iam-mfa-password-holders # not_violation cis_id:1.2
      - manual-ensure-security-questions # cis_id:1.15
      - manual-detailed-billing # cis_id:1.17
      - iam-root-key-access # cis_id:1.12
      - iam-root-no-mfa # cis_id:1.13
      - manual-strategic-iam-roles # cis_id:1.18
      - iam-initialization-access-key # cis_id:1.23
      - manual-contact-details # cis_id:1.19
      - manual-security-contact # cis_id:1.20
      - manual-resource-instance-access # cis_id:1.21
      - manual-full-privilege-user # cis_id:1.24
      - manual-appropriate-sns-subscribers # cis_id:3.15 #meta_nist_171_id "3.14.6, 3.14.7"
      - manual-least-access-routing-tables # cis_id:4.5
      - manual-obscure-auth-info # meta_nist_171_id "3.5.11"
      - manual-least-access-routing-tables # cis_id:4.5
      - manual-maintenance-records #meta_nist_171_id "3.7.1, 3.7.2, 3.7.3"
      - manual-approved-monitored-maintenance # meta_nist_171_id "3.7.1, 3.7.2, 3.7.3"
      - manual-component-removal-approval #meta_nist_171_id "3.7.1, 3.7.2, 3.7.3"
      # this *-is-admin rules require additional privs on the role assigned to cloudcoreo:
      #        {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["iam:SimulateCustomPolicy","iam:SimulatePrincipalPolicy"],"Resource":["*"]}]}
    description: "Which rules would you like to run? Possible values are iam-inventory-users iam-inventory-roles iam-inventory-policies iam-inventory-groups iam-unusediamgroup iam-multiple-keys iam-root-multiple-keys iam-inactive-key-no-rotation iam-active-key-no-rotation iam-missing-password-policy iam-passwordreuseprevention iam-expirepasswords iam-no-mfa iam-root-active-password iam-user-attached-policies iam-password-policy-uppercase iam-password-policy-lowercase iam-password-policy-symbol iam-password-policy-number iam-password-policy-min-length iam-root-access-key-1 iam-root-access-key-2 iam-cloudbleed-passwords-not-rotated iam-support-role iam-user-password-not-used iam-unused-access iam-no-hardware-mfa-root iam-active-root-user iam-mfa-password-holders manual-ensure-security-questions manual-detailed-billing iam-root-key-access iam-root-no-mfa manual-strategic-iam-roles iam-initialization-access-key manual-contact-details manual-security-contact manual-resource-instance-access manual-full-privilege-user manual-appropriate-sns-subscribers manual-least-access-routing-tables iam-user-is-admin iam-instance-role-is-admin"  
  AUDIT_AWS_REGIONS:
    description: "List of AWS regions to check. Default is all regions. Choices are us-east-1,us-east-2,us-west-1,us-west-2,ca-central-1,ap-south-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-northeast-1,eu-central-1,eu-west-1,eu-west-1,sa-east-1"
    required: true
    type: array
    default:
        - us-west-1
  FILTERED_OBJECTS:
    description: "JSON object of string or regex of aws objects to include or exclude and tag in audit"
    required: false
    type: string
    default:
